/*
 * 
 * @author  Steve
 * deleteattributeJDialog.java
 *
 * Created on August 9, 2008, 3:12 PM
 */
/**
 * jButton1:         Delete attribute action
 * jButton2:         Close deleteattributeJDialog;
 * jComboBox1        list of attrubutes
 */
public class deleteattributeJDialog extends javax.swing.JDialog {

    /** Creates new form deleteattributeJDialog */
    public deleteattributeJDialog(java.awt.Frame parent, boolean modal, Database data, int mode) {
        super(parent, modal);
        this.data = data;
        this.mode = mode;
        this.validator = new UIValidator(this.data);
        initComponents();
        if (this.mode == 0) {
            this.setTitle("Delete Professor Attribute");
            int size = this.data.getNumberProfessorAttributes();
            String[] attNames = new String[size];
            for (int i = 0; i < size; i++) {
                attNames[i] = data.getProfessorAttributeByIndex(i).toString();
            }
            jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(attNames));
        }
        if (this.mode == 1) {
            this.setTitle("Delete Course Attribute");
            int size = this.data.getNumberCourseAttributes();
            String[] attNames = new String[size];
            for (int i = 0; i < size; i++) {
                attNames[i] = data.getCourseAttributeByIndex(i).toString();
            }
            jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(attNames));
        }
        this.setLocationRelativeTo(parent);
        this.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Attribute");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox1, 0, 183, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton2});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
    this.dispose();
}//GEN-LAST:event_jButton2ActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
    if (jComboBox1.getSelectedIndex() != -1) {
        if (mode == 0) {
            if (validator.removeProfessorAttribute(jComboBox1.getSelectedItem().toString())) {
                javax.swing.JOptionPane.showMessageDialog(this, "Attribute " + jComboBox1.getSelectedItem().toString() + " has been deleted.");
                this.dispose();
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Can not delete attribute");
            }
        }
        if (mode == 1) {
            if (validator.removeCourseAttribute(jComboBox1.getSelectedItem().toString())) {
                javax.swing.JOptionPane.showMessageDialog(this, "Attribute " + jComboBox1.getSelectedItem().toString() + " has been deleted.");
                this.dispose();
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Can not delete attribute");
            }
        }
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select a attribute.");
    }
}//GEN-LAST:event_jButton1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    // User declaration
    private Database data;
    private int mode;
    private UIValidator validator;
}
