/*
 * editattributeJDialog.java
 *
 * Created on August 12, 2008, 4:07 PM
 */

/**
 *
 * @author  Steve
 */
public class editattributeJDialog extends javax.swing.JDialog {

    /** Creates new form editattributeJDialog */
    public editattributeJDialog(java.awt.Frame parent, boolean modal, Database data, int mode) {
        super(parent, modal);
        initComponents();
        this.data = data;
        this.mode = mode;
        this.validator = new UIValidator(this.data);
        if (this.mode == 0) {
            this.setTitle("Edit Professor Attribute");
            int size = this.data.getNumberProfessorAttributes();
            String[] attNames = new String[size];
            for (int i = 0; i < size; i++) {
                attNames[i] = data.getProfessorAttributeByIndex(i).toString();
            }
            jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(attNames));
        }
        if (this.mode == 1) {
            this.setTitle("Delete Course Attribute");
            int size = this.data.getNumberCourseAttributes();
            String[] attNames = new String[size];
            for (int i = 0; i < size; i++) {
                attNames[i] = data.getCourseAttributeByIndex(i).toString();
            }

            jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(attNames));

        }
        this.setLocationRelativeTo(parent);
        this.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Name");

        jLabel2.setText("Value");

        jButton1.setText("Edit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, 0, 151, Short.MAX_VALUE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
    if (jComboBox1.getSelectedIndex() != -1) {
        if (!jTextField2.getText().equals("")) {
            if (mode == 0) {
                if (validator.editProfessorAttributeProperties(jComboBox1.getSelectedItem().toString(), jTextField2.getText())) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Attribute " + jComboBox1.getSelectedItem().toString() + " has been changed.");
                    this.dispose();
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "Can not edit attribute");
                }
            }
            if (mode == 1) {
                if (validator.editCourseAttributeProperties(jComboBox1.getSelectedItem().toString(), jTextField2.getText())) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Attribute " + jComboBox1.getSelectedItem().toString() + " has been changed.");
                    this.dispose();
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "Can not edit attribute");
                }
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter a value.");
        }
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select a attribute.");
    }

}//GEN-LAST:event_jButton1ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
    this.dispose();
}//GEN-LAST:event_jButton2ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
    // User declaration
    private Database data;
    private int mode;
    private UIValidator validator;
}
